### ISSUE TITLE
[Issue] Un-Flat Bedrock in Vanilla biomes when coupled with BYG/BOP

### ISSUE THREAD

**Issue by 1TruGod** [nanite/Flat-Bedrock#10]
### Mod version

1.18.2

### Forge mod loader version

40.0.36

### Repeatable?

- [X] Yes

### Link to log files

[latest.log](https://github.com/nanite/Flat-Bedrock/files/8403545/latest.log)

### Steps to reproduce the issue

1. Installed clean 1.18.2 with Forge
2. Installed the following by itself and it works fine: flatbedrock-1.4.2-build.9+mc1.18.2
3. Problem arises if I go and add BOP/BYG/TerraBlender.
4. BOP/BYG Biomes on a new world will generate flat bedrock, but vanilla Minecraft Biomes like Plains, Rivers, Snowy Beach etc now generate normal bedrock (un-flat).

### Description of the issue you are having

It appears that when installing this mod along BOP/BYG it makes the bedrock on BOP/BYG biomes flat, but renders vanilla minecraft biomes to not have flat bedrock. Unsure if this could this be an issue with those other mods? If it is, then apologies. 

Screenshot shows flat bedrock in a BYG Biome.
![2022-04-02_19 38 39](https://user-images.githubusercontent.com/87902965/161405175-f1bdabe9-e7f9-466e-86ea-71758f0191ef.png)

Screenshot shows bedrock stagnating like normal in Default Minecraft Snowy Beach Biome.
![2022-04-02_19 39 22](https://user-images.githubusercontent.com/87902965/161405176-2b0173aa-6c32-493a-9d80-c44bfa6ed552.png)

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
So I have overridden the vanilla bedrock generator, these mods have their own generators, I added support for BOP in 1.18.1 could be they have changed something so it doesn't work anymore,
Ill see if I can do anything about when I have time

**Comment by SinFlame** [comment]
Used only Terrablender and it causes this issue

**Comment by Raidobw2** [comment]
Function and package name may have changed to TerraBlender instead of BoP handling the code as before https://github.com/nanite/Flat-Bedrock/blob/a0333d1ed6296fe4326846fe7f5cde2ce3c4541b/src/main/java/com/sunekaer/mods/flatbedrock/mixin/FlatBedrockBOPMixin.java#L10
https://github.com/Glitchfiend/TerraBlender/blob/TB-1.18.2-1.x.x/Common/src/main/java/terrablender/worldgen/TBSurfaceRuleData.java

**Comment by Sunekaer** [comment]
fixed 9ec1bbccaef6a170850c6b6073238f5b28dee7af
