### ISSUE TITLE
[Bug]: Flat Bedrock is incompatible with the cave biomes from Terralith

### ISSUE THREAD

**Issue by James103** [nanite/Flat-Bedrock#11]
### Mod version

flatbedrock-1.4.2-build.10+mc1.18.2 and Terralith_v2.2.1a

### Forge mod loader version

40.1.20

### Repeatable?

- [X] Yes

### Link to log files

Paste.ee link: https://paste.ee/p/6AvkR
Modpack: Direwolf20 1.18 version 1.2.0 (with some modifications)

### Steps to reproduce the issue

1. Generate a new world with Flat Bedrock and Terralith installed.
2. Mine down until you are at Y &lt; -59.
3. Notice there's bedrock above Y = -64.

### Description of the issue you are having

When Flat Bedrock is installed alongside Terralith, Terralith's transition layers (more specifically, the transition layer for deepslate to bedrock) overrides that of Flat Bedrock. This results in bedrock occupying the bottom 5 layers like in vanilla instead of the bottom layer only as expected by Flat Bedrock.

### Information

- [X] I have provided as much information as possible

**Comment by Apollounknowndev** [comment]
I'm relatively sure this is unfixable. This mod overrides the vanilla surface rules to have flat bedrock generation, but Terralith will override those changes and there's no way Terralith can be changed to not override them.

**Comment by Apollounknowndev** [comment]
I was wrong, the 1.20 version of the mod no longer has this issue. This report can probably be closed, then.
