### ISSUE TITLE
[Issue] Bedrock is not flat in other dimensions

### ISSUE THREAD

**Issue by Nevrai** [nanite/Flat-Bedrock#13]
Bedrock generates as per vanilla standards in other dimensions, such as [The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest).

It would be fabulous if you could add a config file or command for adding dimension IDs that Flat Bedrock would function in!

#### Repeatable?

* [X] Yes

#### Information

* [X] I have provided as much information as possible

### Versions

* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **Flat Bedrock:** 1.4.2-build.10 (latest for 1.18.2)

**Comment by Sunekaer** [comment]
I only replace the vanilla bedrock generator so it sounds like they have their own generator and that would be why
