### ISSUE TITLE
[Issue] Does not flatten bedrock generation on servers

### ISSUE THREAD

**Issue by KeithLerner** [nanite/Flat-Bedrock#14]
### Mod version

1.4.2-build.10+mc1.18.2

### Forge mod loader version

40.1.84

### Repeatable?

- [X] Yes

### Link to log files

The mod does not show up anywhere in the log files when searching for the version filename or any subset of the words/numbers in the filename. 

### Steps to reproduce the issue

Install mod on server.
Generate new world.
Dig down to bedrock to verify.

### Description of the issue you are having

The bedrock does not generate flat when generation happens on a server. The mod also is not showing up anywhere in the logs despite being in the mod folder

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
log?
