### ISSUE TITLE
[Issue]/Question, is there config file to setup mod?

### ISSUE THREAD

**Issue by esvarc** [nanite/Flat-Bedrock#22]
### Minecraft Version

1.20.1

### Modloader

forge-1.20.1-47.2.0-installer.jar 

### Mod version

flatbedrock-forge-3.0.1-build.18+mc1.20.1.jar

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

None

### Description of the issue you are having

I'm looking in vain for the config files to set up. I found a guide on the Internet that describes the configuration files in the directory /config/flatbedrock/dimensions/. However, with a clean install and a newly generated world, I found no such configuration files.

In addition, I think the instructions at https://www.9minecraft.net/flat-bedrock-mod/ have the wrong dimensionID for Nether and Overworld. Overworld should be 0 and nether should be -1

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
Never use 9minecraft, always use curseforge..
https://www.curseforge.com/minecraft/mc-mods/flat-bedrock no config.
