### ISSUE TITLE
[Issue] Initial startup crash

### ISSUE THREAD

**Issue by Cynix32** [nanite/Flat-Bedrock#4]
### Mod version

flatbedrock-1.2.0-build.1+mc1.16.5.jar

### Forge mod loader version

36.2.2

### Repeatable?

- [ ] Yes

### Description of the issue you are having

Crash during the initial setup phase very early at startup.
No crashlog generated in the crash-reports folder as the crash occurs very early into starting the game, but here is what I could extract from the console:
https://pastebin.com/CJQXdump

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
Should be fixed with the version i just pushed, let me know if it doesn't.

Thanks.
