### ISSUE TITLE
[Feature request] BOP support

### ISSUE THREAD

**Issue by aerialspring** [nanite/Flat-Bedrock#8]
### Mod version

1.4.0-build.6

### Forge mod loader version

39.0.66

### Repeatable?

- [X] Yes

### Link to log files

Bedrock is not flat. Screenshot: https://ibb.co/ccKRYM4
Using modpack [ScumPack X](https://www.curseforge.com/minecraft/modpacks/scumpack-x-for-1-18-1) for which I am one of the developers. This was working as of forge 39.0.63

### Steps to reproduce the issue

1. Load world.
2. Dig to bedrock (or use World Stripper to view)
3. See that it is not flat.

### Description of the issue you are having

Bedrock layer in OW is not flat.

### Information

- [X] I have provided as much information as possible

**Comment by Sunekaer** [comment]
Just tested on 39.0.66 and it works for me, does this still happen if you disable any world gen mods you have?

**Comment by aerialspring** [comment]
No it works without BOP installed. Something I noticed was that when BOP is installed, the bedrock is flat in non-BOP biomes but not in BOP-biomes. It's very strange. So the issue seems to be that this mod isn't interacting with BOP correctly. Anything that can be done on my end to fix it? Many modpacks use BOP so this functionality would be desirable. :) Thanks!

**Comment by Sunekaer** [comment]
Okay, so sounds like bop has their own bedrock generator as I override the vanilla generator, I'm changing this to be a feature request and not a bug
